// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const UNAUTHORIZED = 'UNAUTHORIZED'
export const ON_LOGIN = 'ON_LOGIN'
export const SAVE_USER = 'SAVE_USER'
export const FETCH_USER_BUSY = 'FETCH_USER_BUSY'